"""Add processing fields to object

Revision ID: 02d2ae4ca13d
Revises: fdbb4047efea
Create Date: 2024-04-24 10:36:23.356448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02d2ae4ca13d'
down_revision: Union[str, None] = 'fdbb4047efea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputobject', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('inputobject', sa.Column('time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputobject', 'time_seconds')
    op.drop_column('inputobject', 'fps')
    # ### end Alembic commands ###
