"""Add sensor data

Revision ID: 2852b3ff35c0
Revises: a3ada9625247
Create Date: 2023-11-09 11:41:14.412762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2852b3ff35c0'
down_revision: Union[str, None] = 'a3ada9625247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordata',
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('instrument_seq', sa.Integer(), nullable=False),
    sa.Column('temperature_1', sa.Float(), nullable=True),
    sa.Column('temperature_2', sa.Float(), nullable=True),
    sa.Column('temperature_3', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sensordata_humidity'), 'sensordata', ['humidity'], unique=False)
    op.create_index(op.f('ix_sensordata_id'), 'sensordata', ['id'], unique=False)
    op.create_index(op.f('ix_sensordata_instrument_seq'), 'sensordata', ['instrument_seq'], unique=False)
    op.create_index(op.f('ix_sensordata_iterator'), 'sensordata', ['iterator'], unique=False)
    op.create_index(op.f('ix_sensordata_temperature_1'), 'sensordata', ['temperature_1'], unique=False)
    op.create_index(op.f('ix_sensordata_temperature_2'), 'sensordata', ['temperature_2'], unique=False)
    op.create_index(op.f('ix_sensordata_temperature_3'), 'sensordata', ['temperature_3'], unique=False)
    op.create_index(op.f('ix_sensordata_time'), 'sensordata', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensordata_time'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_temperature_3'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_temperature_2'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_temperature_1'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_iterator'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_instrument_seq'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_id'), table_name='sensordata')
    op.drop_index(op.f('ix_sensordata_humidity'), table_name='sensordata')
    op.drop_table('sensordata')
    # ### end Alembic commands ###
