"""Initial DB with Submission object

Revision ID: 2abbbe9c2c21
Revises: 
Create Date: 2024-03-01 15:43:37.407642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2abbbe9c2c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('time_added_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_index(op.f('ix_submission_iterator'), 'submission', ['iterator'], unique=False)
    op.create_index(op.f('ix_submission_name'), 'submission', ['name'], unique=False)
    op.create_index(op.f('ix_submission_time_added_utc'), 'submission', ['time_added_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_time_added_utc'), table_name='submission')
    op.drop_index(op.f('ix_submission_name'), table_name='submission')
    op.drop_index(op.f('ix_submission_iterator'), table_name='submission')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
