"""ADd parts JSON column

Revision ID: 2d47fc071033
Revises: 1d48dc4b8e9b
Create Date: 2024-04-11 15:17:34.177710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d47fc071033'
down_revision: Union[str, None] = '1d48dc4b8e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('parts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'parts')
    # ### end Alembic commands ###
