"""Add unique constraint on processing order

Revision ID: 5765d24aa613
Revises: 8041943d6cd9
Create Date: 2024-04-26 13:23:26.180633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5765d24aa613'
down_revision: Union[str, None] = '8041943d6cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('no_same_order_constraint', 'inputobjectassociations', ['processing_order', 'submission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('no_same_order_constraint', 'inputobjectassociations', type_='unique')
    # ### end Alembic commands ###
