"""Add extra columns to Sensor

Revision ID: 63afeb63c97d
Revises: f0cdbc3b3150
Create Date: 2023-11-16 16:11:25.451565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision: str = '63afeb63c97d'
down_revision: Union[str, None] = 'f0cdbc3b3150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sensor', sa.Column('elevation', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('time_recorded_at_utc', sa.DateTime(), nullable=True))
    op.add_column('sensor', sa.Column('time_ingested_at_utc', sa.DateTime(), nullable=False, server_default=func.now()))
    op.alter_column('sensor', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_sensor_time_ingested_at_utc'), 'sensor', ['time_ingested_at_utc'], unique=False)
    op.create_index(op.f('ix_sensor_time_recorded_at_utc'), 'sensor', ['time_recorded_at_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_time_recorded_at_utc'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_time_ingested_at_utc'), table_name='sensor')
    op.alter_column('sensor', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sensor', 'time_ingested_at_utc')
    op.drop_column('sensor', 'time_recorded_at_utc')
    op.drop_column('sensor', 'elevation')
    op.drop_column('sensor', 'comment')
    # ### end Alembic commands ###
