"""Add transect table


Revision ID: 73c7306d0019
Revises: 9b3f99b1ef18
Create Date: 2024-05-21 13:13:39.569045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73c7306d0019'
down_revision: Union[str, None] = '9b3f99b1ef18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transect',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_transect_id'), 'transect', ['id'], unique=False)
    op.create_index(op.f('ix_transect_iterator'), 'transect', ['iterator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transect_iterator'), table_name='transect')
    op.drop_index(op.f('ix_transect_id'), table_name='transect')
    op.drop_table('transect')
    # ### end Alembic commands ###
