"""Add all parts received field

Revision ID: 8041943d6cd9
Revises: 8d7422db3562
Create Date: 2024-04-24 11:51:54.978686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8041943d6cd9"
down_revision: Union[str, None] = "8d7422db3562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inputobject",
        sa.Column(
            "all_parts_received",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inputobject", "all_parts_received")
    # ### end Alembic commands ###
