"""Add time of last part update

Revision ID: 8d7422db3562
Revises: 570ab5d238cb
Create Date: 2024-04-24 11:50:38.802473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d7422db3562'
down_revision: Union[str, None] = '570ab5d238cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputobject', sa.Column('last_part_received_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputobject', 'last_part_received_utc')
    # ### end Alembic commands ###
