"""Add inputobject table and link table

Revision ID: 8fc044200f13
Revises: b1538c2d0bad
Create Date: 2024-03-07 09:24:50.119741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fc044200f13'
down_revision: Union[str, None] = 'b1538c2d0bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputobject',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('hash_md5sum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('time_added_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_inputobject_filename'), 'inputobject', ['filename'], unique=False)
    op.create_index(op.f('ix_inputobject_id'), 'inputobject', ['id'], unique=False)
    op.create_index(op.f('ix_inputobject_iterator'), 'inputobject', ['iterator'], unique=False)
    op.create_index(op.f('ix_inputobject_time_added_utc'), 'inputobject', ['time_added_utc'], unique=False)
    op.create_table('inputobjectassociations',
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('input_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('submission_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('input_id', 'submission_id', name='no_same_link_constraint')
    )
    op.create_index(op.f('ix_inputobjectassociations_input_id'), 'inputobjectassociations', ['input_id'], unique=False)
    op.create_index(op.f('ix_inputobjectassociations_iterator'), 'inputobjectassociations', ['iterator'], unique=False)
    op.create_index(op.f('ix_inputobjectassociations_submission_id'), 'inputobjectassociations', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inputobjectassociations_submission_id'), table_name='inputobjectassociations')
    op.drop_index(op.f('ix_inputobjectassociations_iterator'), table_name='inputobjectassociations')
    op.drop_index(op.f('ix_inputobjectassociations_input_id'), table_name='inputobjectassociations')
    op.drop_table('inputobjectassociations')
    op.drop_index(op.f('ix_inputobject_time_added_utc'), table_name='inputobject')
    op.drop_index(op.f('ix_inputobject_iterator'), table_name='inputobject')
    op.drop_index(op.f('ix_inputobject_id'), table_name='inputobject')
    op.drop_index(op.f('ix_inputobject_filename'), table_name='inputobject')
    op.drop_table('inputobject')
    # ### end Alembic commands ###
