"""Add percentage covers JSON column

Revision ID: 9b3f99b1ef18
Revises: 5765d24aa613
Create Date: 2024-04-29 09:03:20.311797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b3f99b1ef18'
down_revision: Union[str, None] = '5765d24aa613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('percentage_covers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'percentage_covers')
    # ### end Alembic commands ###
