"""Add indexes on owner column and set as non nullable

Revision ID: a153c3f14df3
Revises: 43c9334ac306
Create Date: 2024-06-11 15:19:17.748331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a153c3f14df3'
down_revision: Union[str, None] = '43c9334ac306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inputobject', 'owner',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_inputobject_owner'), 'inputobject', ['owner'], unique=False)
    op.alter_column('submission', 'owner',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_submission_owner'), 'submission', ['owner'], unique=False)
    op.alter_column('transect', 'owner',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_transect_owner'), 'transect', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transect_owner'), table_name='transect')
    op.alter_column('transect', 'owner',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_submission_owner'), table_name='submission')
    op.alter_column('submission', 'owner',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_inputobject_owner'), table_name='inputobject')
    op.alter_column('inputobject', 'owner',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
