"""Add status columns

Revision ID: b1538c2d0bad
Revises: 2abbbe9c2c21
Create Date: 2024-03-05 10:52:31.730574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b1538c2d0bad"
down_revision: Union[str, None] = "2abbbe9c2c21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set previous rows to have processing_has_started and processing_completed_successfully as False

    op.add_column(
        "submission",
        sa.Column(
            "processing_has_started",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "submission",
        sa.Column(
            "processing_completed_successfully",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "processing_completed_successfully")
    op.drop_column("submission", "processing_has_started")
    # ### end Alembic commands ###
