"""Update field names, foreign keys and constraints on link table

Revision ID: b86e764de041
Revises: 8fc044200f13
Create Date: 2024-03-07 09:38:53.840305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b86e764de041'
down_revision: Union[str, None] = '8fc044200f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputobjectassociations', sa.Column('input_object_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_index('ix_inputobjectassociations_input_id', table_name='inputobjectassociations')
    op.drop_constraint('no_same_link_constraint', 'inputobjectassociations', type_='unique')
    op.create_unique_constraint('no_same_link_constraint', 'inputobjectassociations', ['input_object_id', 'submission_id'])
    op.create_index(op.f('ix_inputobjectassociations_input_object_id'), 'inputobjectassociations', ['input_object_id'], unique=False)
    op.create_foreign_key(None, 'inputobjectassociations', 'submission', ['submission_id'], ['id'])
    op.create_foreign_key(None, 'inputobjectassociations', 'inputobject', ['input_object_id'], ['id'])
    op.drop_column('inputobjectassociations', 'input_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputobjectassociations', sa.Column('input_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inputobjectassociations', type_='foreignkey')
    op.drop_constraint(None, 'inputobjectassociations', type_='foreignkey')
    op.drop_index(op.f('ix_inputobjectassociations_input_object_id'), table_name='inputobjectassociations')
    op.drop_constraint('no_same_link_constraint', 'inputobjectassociations', type_='unique')
    op.create_unique_constraint('no_same_link_constraint', 'inputobjectassociations', ['input_id', 'submission_id'])
    op.create_index('ix_inputobjectassociations_input_id', 'inputobjectassociations', ['input_id'], unique=False)
    op.drop_column('inputobjectassociations', 'input_object_id')
    # ### end Alembic commands ###
