"""Add time periods and fps

Revision ID: c1d3c288748f
Revises: 4696f4220f0f
Create Date: 2024-04-02 16:52:12.473208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1d3c288748f'
down_revision: Union[str, None] = '4696f4220f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('submission', sa.Column('time_seconds_start', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('time_seconds_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'time_seconds_end')
    op.drop_column('submission', 'time_seconds_start')
    op.drop_column('submission', 'fps')
    # ### end Alembic commands ###
