"""Change parts column to object table

Revision ID: f73237957346
Revises: 2d47fc071033
Create Date: 2024-04-11 15:19:53.009942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f73237957346'
down_revision: Union[str, None] = '2d47fc071033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputobject', sa.Column('parts', sa.JSON(), nullable=True))
    op.drop_column('submission', 'parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('parts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('inputobject', 'parts')
    # ### end Alembic commands ###
